### PR TITLE
Simplify FROM and TO logic

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by cclauss** [comment]
OK.  Ready for review.

**Comment by akinjide** [comment]
Can you update the base branch to develop instead of master

**Comment by cclauss** [comment]
Oh man... Just merge the commit.

NEXT time I will submit PRs to the develop branch but for this ~200 line file that seems like overkill.  If you want PRs submitted to the develop branch, you need to document that in the README or CONTRIBUTING docs.

**Comment by akinjide** [comment]
Thanks for the feedback. I have merged the other PR. Will be released under v3

**Pull request closed without merging**
